# Process config example for dataset

# global parameters
project_name: 'demo-cifar-process'
dataset_path: '/Users/chenminghua/project/data-juicer/cifar10_data.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

image_key: 'image'

export_path: './outputs/demo-process/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: True
keep_hashes_in_res_ds: True

# process schedule
# a list of several process operators with their arguments
process:
  - image_blurriness_filter:
  - image_brightness_filter:
  - image_deduplicator:
  - image_feature_extract_generator:
  - image_caption_generator:
  - feature_reduce_generator:

