# Process config example for dataset

# global parameters
project_name: 'demo-gn6'
dataset_path: './demos/data_gn6/gn_all.jsonl'  # path to your dataset directory or file
np: 112  # number of subprocess to process your dataset

export_path: './outputs/demo-gn6/demo-processed_all.jsonl'
# keep_cleaning_stas_in_res_ds: False
# keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
  - image_validation_filter:
  - point_cloud_validation_filter:
  - general_file_validation_filter:
      general_file_key: 'hardware_config'
  # - image_blurriness_filter:
  # - image_brightness_filter:
  # - image_deduplicator:
  # - cleanvision_mycleanlab:
  # - image_feature_extract_generator:
  # - image_caption_generator:
  # - feature_reduce_generator:

