# Process config example for dataset

# global parameters
project_name: 'demo-image-dedup'
dataset_path: '/mnt/share_disk/wangdaming/XMT0325/XMT0325_bundle_paths_wide.jsonl'  # path to your dataset directory or file
np: 16  # number of subprocess to process your dataset

image_key: 'images'

export_path: './outputs/demo-vaquitai/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: False
keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
  - image_deduplicator:
