# Process config example for dataset

# global parameters
project_name: 'demo-mtbuller'
dataset_path: '/home/beacon/data-juicer/demos/data_image/cifar10_data_dup.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

image_key: 'image'

export_path: './outputs/demo-mtbuller/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: False
keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
  - image_blurriness_filter:
  - image_brightness_filter:
  - image_deduplicator:
  - cleanvision_mycleanlab:
  - image_feature_extract_generator:
  - image_caption_generator:
  - feature_reduce_generator:

