# Process config example for dataset

# global parameters
project_name: 'demo-gn'
dataset_path: './demos/data_gn/gn.jsonl'  # path to your dataset directory or file
np: 112  # number of subprocess to process your dataset

image_key: 'image'

export_path: './outputs/demo-gn/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: False
keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
  - image_validation_filter:
  # - image_blurriness_filter:
  # - image_brightness_filter:
  - image_deduplicator:
  - cleanvision_mycleanlab:
  # - image_feature_extract_generator:
  # - image_caption_generator:
  # - feature_reduce_generator:

