# Process config example for dataset

# global parameters
open_tracer: True
project_name: 'demo-vaquitai'
dataset_path: './demos/vaquitai/data/cifar10_mini.jsonl'  # path to your dataset directory or file
np: 1  # number of subprocess to process your dataset

image_key: 'images'
trace_num: 100

export_path: './outputs/demo-vaquitai/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: False
keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
  - image_validation_filter:
  # - image_aspect_ratio_filter:
  # - image_deduplicator:
  - cleanvision_mycleanlab:
  # - image_feature_extract_generator:
  # - image_caption_generator:
  # - feature_reduce_generator:

