# Process config example for dataset

# global parameters
project_name: 'demo-gn'
dataset_path: './demos/vaquita/data/cifar10_mini.jsonl'  # path to your dataset directory or file
np: 16  # number of subprocess to process your dataset

image_key: 'image'

export_path: './outputs/demo-gn/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: False
keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
  - image_validation_filter:
  # - image_blurriness_filter:
  # - image_brightness_filter:
  - image_deduplicator:
  - cleanvision_mycleanlab:
  - image_feature_extract_generator:
  - image_caption_generator:
  - feature_reduce_generator:

