# Process config example for dataset

# global parameters
open_tracer: True
project_name: 'demo-vaquitai'
# dataset_path: './demos/vaquitai/data/cifar10_mini.jsonl'  # path to your dataset directory or file
dataset_path: '/root/project/Vaquitai/demos/vaquitai/data/cifar10_mini.jsonl'  # path to your dataset directory or file
np: 1  # number of subprocess to process your dataset

image_key: 'images'
trace_num: 100000000

export_path: './outputs/demo-vaquitai/demo-processed.jsonl'
keep_cleaning_stas_in_res_ds: False
keep_hashes_in_res_ds: False

# process schedule
# a list of several process operators with their arguments
process:
#   - document_deduplicator:
#   - character_repetition_filter:
#   - word_repetition_filter:
  # - phrase_grounding_recall_filter:
  # - text_entity_dependency_filter:
  # - perplexity_filter:
  # - image_validation_filter:
  # - image_shape_filter:
  # - image_aspect_ratio_filter:
  # - image_deduplicator:
  # - cleanvision_mycleanlab:
  # - image_text_similarity_filter:
  #     min_score: 0.2
  # - image_text_matching_filter:
  # - image_watermark_filter:
  # - image_nsfw_filter:
  - image_feature_extract_generator:
  - image_caption_generator:
  - feature_reduce_generator:
  - image_deduplicator:
  - cleanvision_mycleanlab:
  - image_text_matching_filter:
