credentials:
  usernames:
    admin:
      email: admin@gmail.com
      logged_in: False # Will be managed automatically
      name: admin
      password: admin # Will be hashed automatically
    test:
      email: test@gmail.com
      logged_in: False # Will be managed automatically
      name: test
      password: test # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com